### ISSUE TITLE
Save background and fullscreen defaults

### ISSUE THREAD

**Issue by maebert** [maebert/themostdangerouswritingapp#16]
From Email:

> Hi Manuel,
> 
> Thanks a million for making the Most Dangerous Writing App. It’s great for writing and seems to be improving my ability to meditate too! Nice work!
> 
> One question: is there any way to set the display defaults? I like to use dark background and fullscreen. Currently I have to select these options every time.
> 
> Kind regards,
> 
> Pat

**Comment by v-stickykeys** [comment]
browser won't allow you to autoset fullscreen as it is a security violation. also fullscreen can only be set for a single page/frame so it won't be transferred over across the site. however I fixed the save background using local storage

**Comment by maebert** [comment]
Agreed, and even it saving fullscreen settings were possible the experience would be at best confusing for a lot of users. Thanks for implementing the night mode though!
