### ISSUE TITLE
Can't get back to the writing after putting in email

### ISSUE THREAD

**Issue by TheShashank** [maebert/themostdangerouswritingapp#17]
Hey there
 
First of all, I love the app! I've been using it a lot. Thanks for making it open source.

Sometimes, when I fail and the "You failed." screen pops up - it does not let me continue once I subscribe to the newsletter. It makes me start over and my data does not persist.

Is there a way this could be fixed?

Thanks

**Comment by v-stickykeys** [comment]
Seems this is only a problem in hardcore mode. Can you confirm @TheShashank ?

**Comment by TheShashank** [comment]
Nope, it's true for both Hardcore and regular modes

**Comment by v-stickykeys** [comment]
Thanks. PR should fix the issue

**Comment by maebert** [comment]
Thanks for reporting @TheShashank and fixing it @thevaleriemack!
