### ISSUE TITLE
After running in command promt 'npm run build' - you get error Unknown argument: mode

### ISSUE THREAD

**Issue by vikegart** [maebert/themostdangerouswritingapp#21]
https://github.com/maebert/themostdangerouswritingapp/blob/f45f20e56ecaec1c92a64205053d46584954fd32/mdwa/package.json#L53

Hi, just clone and run 
`npm i`
 then
 `npm run build`
 and getting this error. Unknown argument: mode.
 Maybe it's a problem with webpack? 
'cause `npm run start` fork fine

**Comment by vikegart** [comment]
**FIXED**, just change 
https://github.com/maebert/themostdangerouswritingapp/blob/f45f20e56ecaec1c92a64205053d46584954fd32/mdwa/package.json#L53
  to
`"build": "node scripts/build.js",`

and add scss files support in your webpack.prod config, like I am done in my last commit https://github.com/vikegart/themostdangerouswritingapp/commit/9e2b25694ef18e5ce2b93be997624200d8520d4e

so, you can see, that it's working fine on my [gh-pages](https://vikegart.github.io/themostdangerouswritingapp/)

**Comment by maebert** [comment]
Hey @vikegart, I see you found my super hidden branch to port MDWA to React :) It's definitely WIP, but would you care to open a PR against the `react` branch to fix this?

**Comment by vikegart** [comment]
@maebert well done, check it :)

P.S.
for testing production build I highly recommend use [node http-server](https://www.npmjs.com/package/http-server) - just install it globally and switched to `build` folder and write `http-server`
