### ISSUE TITLE
wrong word count on empty document

### ISSUE THREAD

**Issue by zumoshi** [maebert/themostdangerouswritingapp#25]
```js
''.split(/\s+/).length // == 1
```
code in [update_stats ](https://github.com/maebert/themostdangerouswritingapp/blob/e104f2553d87eeddc8fd7fde4d7dc11bc2eb2547/js/app.js#L69) uses the snippet above. pressing any non-character key (e.g. Ctrl) or writing something and then erasing it, will result in an empty document but shows `1 word` at the bottom of the screen instead of 0.

**Comment by maebert** [comment]
Fixed, well spottet!
