### ISSUE TITLE
how to use this app?

### ISSUE THREAD

**Issue by OKdongge** [maebert/themostdangerouswritingapp#34]
as the title,is there any instruction to deploy?

**Comment by myang39** [comment]
A detailed deployment instruction would be really helpful.

**Comment by maebert** [comment]
Have you found the [DEVELOPMENT.md](https://github.com/maebert/themostdangerouswritingapp/blob/master/DEVELOPMENT.md)? 

To quote:

> ## Developing
> 
> 1. `npm install` to install dependencies
> 2. `npm start` to run a development server
> 
> ## Deploying
> 
> Update the version number in `package.json`, then run
> 
> ```
> npm run deploy
> ```
> 
> This will build the app into the `build` folder, and then update the `gh-pages` branch from that.

I know these descriptions are very high-level; what are you struggling with?
