### ISSUE TITLE
Command-line launcher

### ISSUE THREAD

**Issue by teodorlu** [maebert/themostdangerouswritingapp#35]
Hello!

Thanks again for the lovely app. I've been using it quite a bit to get my mind unstuck when I just need to produce some text, and later copyedit. To that purpose, I made a small command line launcher that enables launching the app like this:

    dangerouslywrite

or

    dangerouslywrite 5

Full script:

```bash
#!/bin/bash

QUANTITY="${1:-5}"
UNIT="${2:-minutes}"

firefox -new-window "https://maebert.github.io/themostdangerouswritingapp/#/write?limit=$QUANTITY&type=$UNIT"
```

This might not be novel at all, but I figured I'd share it and let you be the judge. Browser is hard-coded for now. Feel free to close this issue when you've seen it.

Teodor

**Comment by maebert** [comment]
Hey Teodor, this is super neat! I have a hammerspoon hotkey defined for just that too ;)
