### ISSUE TITLE
Add a writing prompt

### ISSUE THREAD

**Issue by ripper234** [maebert/themostdangerouswritingapp#38]
I was using https://www.squibler.io/, which seems to be based of the code of themostdangerouswritingapp, in order to write short stories.

The way it works is that it generates a short sentence AKA writing prompt, and then the usual logic of TMDWA proceeds.

Today, they closed their website and require a login (until yesterday it allowed anon users).

Could we add something like this to TMDWA?

Maybe from https://ineedaprompt.com/ ?

**Comment by ripper234** [comment]
I 😍 TMDWA btw, have been using it without prompt for a long time.
Many thanks for writing it, it's super useful!

**Comment by maebert** [comment]
Hi @ripper234,

in fact, MDWA was acquired by Squibler - Ie. they now own the [domain](http://themostdangerouswritingapp.com) and maintain their own private fork of the source, while the original project remains open source.

You can use theirs at https://www.squibler.io/writing-prompt-generator, which works without login again, and the original one at https://maebert.github.io/themostdangerouswritingapp.
