### ISSUE TITLE
I think I should not accept spaces

### ISSUE THREAD

**Issue by Sneyder2328** [maebert/themostdangerouswritingapp#4]
Al pulsar SPACE el sistema lo detecta igual que a las demas letras, de manera que al presionar esa tecla constantemente se puede permanecer en la App sin perder.
Creo que la solucion seria que en el listener de eventos la tecla SPACE no lo procese de la misma forma que a las demas teclas.
I am sorry, but i do not speak english only  speak spanish. Try translated

**Comment by maebert** [comment]
Buena idea, lo cambie en 55a59d7
