### ISSUE TITLE
function of "Win! Retry?" button is unclear

### ISSUE THREAD

**Issue by yitongzhang** [maebert/themostdangerouswritingapp#5]
I thought the "Win! Retry?" button would reset the timer on the same project. Turns out, it erases the current one and starts a blank page. Might be good to display confirmation box or a note to indicate what it does. 

(sorry if this is the wrong place to report the issue. I'm new to open source projects)

**Comment by madpew** [comment]
I fell for this as well, maybe it should be reworded to "Win! Reset?" or changed to "Win! Continue?" with the code changed to add another "slice" to the current text.

**Comment by maebert** [comment]
Changed it, along with a save button. Does this work?

<img width="595" alt="screen shot 2016-04-27 at 3 19 06 pm" src="https://cloud.githubusercontent.com/assets/1047165/14869914/714b6810-0c8b-11e6-93d5-043cfb3507cb.png">
