### ISSUE TITLE
Must clear clipboard

### ISSUE THREAD

**Issue by mathieu-pousse** [maebert/themostdangerouswritingapp#7]
I spot some guys cheating by coping anything to the clipboard (ctrl + A / ctrl + C)
To really improve productivity we need to clear the clipboard to ensure nobody can save the text !

HIH

**Comment by maebert** [comment]
Problem is that you [can't clear the clipboard with JavaScript](https://stackoverflow.com/questions/7060109/why-is-writing-to-the-clipboard-in-js-considered-a-security-hole/7060586#7060586). Might try and preventing copying anything from caching Ctrl + C keystrokes though.

**Comment by mathieu-pousse** [comment]
Seems feasible to access clipboard with js: https://clipboardjs.com/

On Sun, Apr 17, 2016 at 9:17 PM, Manuel Ebert notifications@github.com
wrote:

> Problem is that you can't clear the clipboard with JavaScript
> https://stackoverflow.com/questions/7060109/why-is-writing-to-the-clipboard-in-js-considered-a-security-hole/7060586#7060586.
> Might try and preventing copying anything from caching Ctrl + C keystrokes
> though.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/maebert/themostdangerouswritingapp/issues/7#issuecomment-211090314

## 

_Mathieu POUSSE | *_06.28.89.08.43*\* |\* _@m_pousse_
_Zenika Ouest_
18, rue de la Monnaie
35000 RENNES

**Comment by maebert** [comment]
I instead prohibited using copying to clipboard altogether, see #6!

**Comment by superj60** [comment]
Hi,

I use cmd+A, cmd+C to save my work if I finish before the timer runs out - rather than sitting and waiting for it. So this update has made my life more difficult...

I have taken a local copy and removed this update but I feel that this should be optional prior to starting a session. If someone is going to cheat then there is no point of using the app.

Jay

**Comment by maebert** [comment]
If you must, you can still Cmd+A and then Right click and select "copy".
