### ISSUE TITLE
Mention somewhere how to save the text

### ISSUE THREAD

**Issue by nicolasreich** [maebert/themostdangerouswritingapp#8]
Hi, first of all thanks for the app, it is fun to use and is helping me quite a bit writing a lengthy report. However I feel there should be a mention somewhere that the regular ctrl/cmd-c does not work. I had finished a paragraph and wanted to copy it back to my main file and I lost all of it. I realise that right-click/copy works, but I think it should be said somewhere so there is no bad surprise on the first use.

**Comment by maebert** [comment]
Thanks for sharing your thoughts! Just to understand, after finishing your time limit it's clear how saving works, right?

**Comment by nicolasreich** [comment]
Yes after finishing it is fine, the situation I was refering to was in the case you're satisfied with the part/paragraph/chapter/whatever you've written before the end of the time limit and want to save it.
